config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resource :account, except: [:new, :create]

  resources :users, except: [:edit, :update], constraints: { id: /\d+/ }
  devise_for :users

  resources :devices

  get 'assignments/:content_class/:content_id/select', controller: :assignments, action: :select, as: :select_device
  post 'assignments/assign', controller: :assignments, action: :assign, as: :assign_device

  resources :themes, shallow: true do
    resources :quizzes

    resources :timelines, shallow: true do
      resources :intervals, except: :index, shallow: true do
        resources :interval_images, except: :index
      end
    end

    resources :video_galleries, shallow: true do
      resources :videos, except: :index
    end

    resources :trailer_galleries, shallow: true do
      resources :trailers, except: :index
    end

    resources :galleries, shallow: true do
      resources :images, except: :index
    end

    resources :playlists, shallow: true do
      resources :tracks, except: [:index, :show]
    end
  end

  namespace :api do
    resources :devices, only: [:show, :update], constraints: { id: /[a-z0-9_-]+/i }

    get 'patron', to: 'cicero#show'
  end

  root to: 'themes#index'
end

app/models/theme.rb
class Theme < ApplicationRecord
  COLORS = {
    "Yellow" => '#fffbbd',
    "Pink" => '#ffddff',
    "Green" => '#bce6bc',
    "Orange" => '#ffd7b3',
    "Blue" => '#b7d7ed',
    "Warm grey" => '#cfd0d0',
    "Purple" => '#dac2ff'
  }.freeze

  has_many :galleries, -> { order(:name) }, dependent: :destroy
  has_many :playlists, -> { order(:name) }, dependent: :destroy
  has_many :quizzes, -> { order(:name) }, dependent: :destroy
  has_many :timelines, -> { order(:name) }, dependent: :destroy
  has_many :video_galleries, -> { order(:name) }, dependent: :destroy
  has_many :trailer_galleries, -> { order(:name) }, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :color, presence: true, format: { with: /\A#[a-f0-9]{6}\z/i }

  def color_name
    COLORS.invert[self.color]
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  def index
    @themes = Theme.all.order(:name)
  end

  # GET /themes/1
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  def create
    @theme = Theme.new(theme_params)

    if @theme.save
      redirect_to @theme, notice: 'Theme was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /themes/1
  def update
    if @theme.update(theme_params)
      redirect_to @theme, notice: 'Theme was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /themes/1
  def destroy
    @theme.destroy

    redirect_to themes_url, notice: 'Theme was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_theme
    @theme = Theme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def theme_params
    params.require(:theme).permit(:name, :color)
  end

end

app/views/themes/_form.html.erb
<%= form_with(model: theme, local: true) do |form| %>
  <%= render 'common/validation_errors', model: theme %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true, id: :theme_name %>
  </div>

  <div class="form-group">
    <%= form.label :color %>
    <%= select_tag 'theme[color]', options_for_select(Theme::COLORS, theme.color || Theme::COLORS.values.first), { id: :theme_color } %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= yield %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @theme %>
<% end %>

app/views/themes/index.html.erb
<h1>Themes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="width:2em; max-width:3em"></th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td>
          <div class="well well-sm" style="background: <%= theme.color %>; width: 3em; margin-bottom: 0"></div>
        </td>
        <td><%= link_to theme.name, theme %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Add theme...', new_theme_path %>
</p>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', themes_path %>
<% end %>

app/views/themes/show.html.erb
<h1>Theme: <%= @theme.name %></h1>

<p>
  <%= link_to 'Edit theme...', edit_theme_path(@theme) %>
  |
  <%= link_to 'Delete theme and content...', @theme, method: :delete, data: { confirm: 'Are you sure you want to delete this theme and all its content?' }, class: "text-danger" %>
</p>

<div class="well" style="background: <%= @theme.color %>">
  <strong>Color:</strong>
  <%= @theme.color_name.try(:capitalize) || "?" %>
  <samp>(<%= @theme.color %>)</samp>
</div>

<h2>Content</h2>

<h3>Galleries</h3>

<% if @theme.galleries.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.galleries.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td><%= model.bilingual? ? "Danish/English" : "Danish" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">No galleries yet</em></p>
<% end %>

<p><%= link_to 'Add gallery...', new_theme_gallery_path(@theme) %></p>

<hr>

<h3>Quizzes</h3>

<% if @theme.quizzes.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.quizzes.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td><%= model.bilingual? ? "Danish/English" : "Danish" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">None</em></p>
<% end %>

<p><%= link_to 'Add quiz...', new_theme_quiz_path(@theme) %></p>

<hr>

<h3>Timelines</h3>

<% if @theme.timelines.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.timelines.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td><%= model.bilingual? ? "Danish/English" : "Danish" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">None</em></p>
<% end %>

<p><%= link_to 'Add timelines...', new_theme_timeline_path(@theme) %></p>

<hr>

<h3>Video Galleries</h3>

<% if @theme.video_galleries.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.video_galleries.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td><%= model.bilingual? ? "Danish/English" : "Danish" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">None</em></p>
<% end %>

<p><%= link_to 'Add video gallery...', new_theme_video_gallery_path(@theme) %></p>

<hr>

<h3>Trailer Galleries</h3>

<% if @theme.trailer_galleries.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.trailer_galleries.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td><%= model.bilingual? ? "Danish/English" : "Danish" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">None</em></p>
<% end %>

<p><%= link_to 'Add trailer gallery...', new_theme_trailer_gallery_path(@theme) %></p>

<hr>

<h3>Playlists</h3>

<% if @theme.playlists.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 20%">Languages</th>
      </tr>
    </thead>
    <tbody>
    <% @theme.playlists.each do |model| %>
      <tr>
        <td>
          <%= link_to model.name, model %>

          <% if model.assigned? %>
            <span class="label label-warning">LIVE</span>
          <% end %>

          <% unless model.presentable? %>
            <span class="label label-danger">Incomplete</span>
          <% end %>
        </td>
        <td>
          <em class="text-muted">N/A</em>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p><em class="text-muted">None</em></p>
<% end %>

<p><%= link_to 'Add playlist...', new_theme_playlist_path(@theme) %></p>