config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resource :account, except: [:new, :create]

  resources :users, except: [:edit, :update], constraints: { id: /\d+/ }
  devise_for :users

  resources :devices

  get 'assignments/:content_class/:content_id/select', controller: :assignments, action: :select, as: :select_device
  post 'assignments/assign', controller: :assignments, action: :assign, as: :assign_device

  resources :themes, shallow: true do
    resources :quizzes

    resources :timelines, shallow: true do
      resources :intervals, except: :index, shallow: true do
        resources :interval_images, except: :index
      end
    end

    resources :video_galleries, shallow: true do
      resources :videos, except: :index
    end

    resources :trailer_galleries, shallow: true do
      resources :trailers, except: :index
    end

    resources :galleries, shallow: true do
      resources :images, except: :index
    end

    resources :playlists, shallow: true do
      resources :tracks, except: [:index, :show]
    end
  end

  namespace :api do
    resources :devices, only: [:show, :update], constraints: { id: /[a-z0-9_-]+/i }

    get 'patron', to: 'cicero#show'
  end

  root to: 'themes#index'
end

app/models/trailer_gallery.rb
class TrailerGallery < ApplicationRecord
  MIN_PRESENTABLE_TRAILER_COUNT = 1
  MAX_TRAILER_COUNT = 30

  include Presentable
  include Assignable
  include Bilingual

  belongs_to :theme, optional: true
  has_many :trailers, dependent: :destroy

  device_kind :screen
  bilingual_associations :trailers

  validates :name, presence: true, uniqueness: true

  # overrides Presentable method
  def presentable?
    self.trailers.count >= MIN_PRESENTABLE_TRAILER_COUNT
  end
end

app/controllers/trailer_galleries_controller.rb
class TrailerGalleriesController < ApplicationController
  include ThematicController

  before_action :set_trailer_gallery, only: [:show, :edit, :update, :destroy]

  # GET /trailer_galleries
  def index
    @trailer_galleries = @theme.trailer_galleries.all
  end

  # GET /trailer_galleries/1
  # GET /trailer_galleries/1.json
  def show
  end

  # GET /trailer_galleries/new
  def new
    @trailer_gallery = @theme.trailer_galleries.new
  end

  # GET /trailer_galleries/1/edit
  def edit
  end

  # POST /trailer_galleries
  def create
    @trailer_gallery = @theme.trailer_galleries.new(trailer_gallery_params)

    if @trailer_gallery.save
      redirect_to @trailer_gallery, notice: 'Trailer gallery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trailer_galleries/1
  def update
    if @trailer_gallery.update(trailer_gallery_params)
      redirect_to @trailer_gallery, notice: 'Trailer gallery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trailer_galleries/1
  def destroy
    @trailer_gallery.destroy

    redirect_to @trailer_gallery.theme, notice: 'Trailer gallery was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trailer_gallery
    @trailer_gallery = TrailerGallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trailer_gallery_params
    params.require(:trailer_gallery).permit(:name)
  end

end

app/views/trailer_galleries/_form.html.erb
<%= form_with(model: trailer_gallery, url: (trailer_gallery.new_record? ? [trailer_gallery.theme, trailer_gallery] : trailer_gallery), local: true) do |form| %>
  <%= render 'common/validation_errors', model: trailer_gallery %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true, id: :trailer_gallery_name %>
    <span class="help-block">
      Required. The name isn't shown publically, it's only for naming the trailer gallery in the CMS.
    </span>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= yield %>
  </div>
<% end %>

app/views/trailer_galleries/edit.html.erb
<h1>Editing Trailer Gallery</h1>

<%= render 'form', trailer_gallery: @trailer_gallery do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @trailer_gallery %>
<% end %>

app/views/trailer_galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trailer Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trailer_galleries.each do |trailer_gallery| %>
      <tr>
        <td><%= trailer_gallery.name %></td>
        <td><%= link_to 'Show', trailer_gallery %></td>
        <td><%= link_to 'Edit', edit_trailer_gallery_path(trailer_gallery) %></td>
        <td><%= link_to 'Destroy', trailer_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add trailer gallery...', new_theme_trailer_gallery_path(@theme) %>

app/views/trailer_galleries/new.html.erb
<h1>New Trailer Gallery</h1>

<%= render 'form', trailer_gallery: @trailer_gallery do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @trailer_gallery.theme %>
<% end %>

app/views/trailer_galleries/show.html.erb
<%= render 'common/assigned_devices', model: @trailer_gallery %>

<%= render 'common/content_title', model: @trailer_gallery do %>
  <%= link_to 'Edit trailer gallery...', edit_trailer_gallery_path(@trailer_gallery) %> |
  <%= link_to 'Delete trailer gallery...', @trailer_gallery, method: :delete, data: { confirm: 'Are you sure you want to delete this trailer gallery and all its trailers?' }, class: "text-danger" %>
<% end %>

<%= render 'common/content_controls', model: @trailer_gallery do %>
  It must contain <%= TrailerGallery::MIN_PRESENTABLE_TRAILER_COUNT %> to <%= TrailerGallery::MAX_TRAILER_COUNT %> trailers.
<% end %>

<h2>Trailers</h2>

<% if @trailer_gallery.trailers.any? %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Languages</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  <% @trailer_gallery.trailers.each do |trailer| %>
    <tr>
      <td>
        <%= link_to trailer.title_da, trailer %>
        <% if trailer.title_en.present? %>
        <br>
        <span class="text-muted"><%= trailer.title_en %></span>
        <% end %>
      </td>
      <td>
        <%= trailer.bilingual? ? "Danish/English" : "Danish" %>
      </td>
      <td>
        <%= link_to "Edit", edit_trailer_path(trailer) %>
      </td>
      <td>
        <%= link_to 'Delete...', trailer, method: :delete, data: { confirm: 'Are you sure you want to delete this trailer?' }, class: "text-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<% else %>

<div class="alert alert-warning">
  This trailer gallery cannot be shown on any devices yet, as it must contain at least 1 trailer.
</div>

<% end %>

<% if @trailer_gallery.trailers.count < TrailerGallery::MAX_TRAILER_COUNT %>
<p>
  <%= link_to 'Add trailer...', new_trailer_gallery_trailer_path(@trailer_gallery) %>
</p>
<% end %>