config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resource :account, except: [:new, :create]

  resources :users, except: [:edit, :update], constraints: { id: /\d+/ }
  devise_for :users

  resources :devices

  get 'assignments/:content_class/:content_id/select', controller: :assignments, action: :select, as: :select_device
  post 'assignments/assign', controller: :assignments, action: :assign, as: :assign_device

  resources :themes, shallow: true do
    resources :quizzes

    resources :timelines, shallow: true do
      resources :intervals, except: :index, shallow: true do
        resources :interval_images, except: :index
      end
    end

    resources :video_galleries, shallow: true do
      resources :videos, except: :index
    end

    resources :trailer_galleries, shallow: true do
      resources :trailers, except: :index
    end

    resources :galleries, shallow: true do
      resources :images, except: :index
    end

    resources :playlists, shallow: true do
      resources :tracks, except: [:index, :show]
    end
  end

  namespace :api do
    resources :devices, only: [:show, :update], constraints: { id: /[a-z0-9_-]+/i }

    get 'patron', to: 'cicero#show'
  end

  root to: 'themes#index'
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  MIN_PRESENTABLE_INTERVAL_COUNT = 2

  include Presentable
  include Assignable
  include Bilingual

  belongs_to :theme, optional: true
  has_many :intervals, dependent: :destroy

  device_kind :screen
  bilingual_associations :intervals

  validates :name, presence: true, uniqueness: true
  validates :title_da, presence: true

  # overrides Presentable method
  def presentable?
    return false if self.intervals.count < MIN_PRESENTABLE_INTERVAL_COUNT
    self.intervals.all?(&:presentable?)
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  include ThematicController

  before_action :set_timeline, only: [:show, :edit, :update, :destroy]

  # GET /timelines
  def index
    @timelines = @theme.timelines.all
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end

  # GET /timelines/new
  def new
    @timeline = @theme.timelines.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  def create
    @timeline = @theme.timelines.new(timeline_params)

    if @timeline.save
      redirect_to @timeline, notice: 'Timeline was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /timelines/1
  def update
    if @timeline.update(timeline_params)
      redirect_to @timeline, notice: 'Timeline was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /timelines/1
  def destroy
    @timeline.destroy

    redirect_to @timeline.theme, notice: 'Timeline was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_timeline
    @timeline = Timeline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def timeline_params
    params.require(:timeline).permit(:name, :title_da, :title_en)
  end

end

app/views/timelines/_form.html.erb
<%= form_with(model: timeline, url: (timeline.new_record? ? [timeline.theme, timeline] : timeline), local: true) do |form| %>
  <%= render 'common/validation_errors', model: timeline %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: 'form-control', id: :timeline_name %>
    <span class="help-block">
      Required. The timeline name isn't shown publically, it's only for naming the timeline in the CMS.
    </span>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h3>Danish (required)</h3>

      <div class="form-group">
        <%= form.label :title_da %>
        <%= form.text_field :title_da, required: true, class: 'form-control', id: :timeline_title_da %>
      </div>
    </div>

    <div class="col-md-6">
      <h3>English</h3>

      <div class="form-group">
        <%= form.label :title_en %>
        <%= form.text_field :title_en, class: 'form-control', id: :timeline_title_en %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= yield %>
  </div>
<% end %>

app/views/timelines/edit.html.erb
<h1>Editing Timeline</h1>

<%= render 'form', timeline: @timeline do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @timeline %>
<% end %>

app/views/timelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timelines</h1>

<table>
  <thead>
    <tr>
      <th>Title da</th>
      <th>Title en</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelines.each do |timeline| %>
      <tr>
        <td><%= timeline.title_da %></td>
        <td><%= timeline.title_en %></td>
        <td><%= link_to 'Show', timeline %></td>
        <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
        <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add timeline...', new_theme_timeline_path(@theme) %>

app/views/timelines/new.html.erb
<h1>New Timeline</h1>

<%= render 'form', timeline: @timeline do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @timeline.theme %>
<% end %>

app/views/timelines/show.html.erb
<%= render 'common/assigned_devices', model: @timeline %>

<%= render 'common/content_title', model: @timeline do %>
  <%= link_to 'Edit timeline...', edit_timeline_path(@timeline) %> |
  <%= link_to 'Delete timeline...', @timeline, method: :delete, data: { confirm: 'Are you sure you want to delete this timeline and all its content?' }, class: "text-danger" %>
<% end %>

<%= render 'common/content_controls', model: @timeline do %>
  It must contain <%= pluralize(Timeline::MIN_PRESENTABLE_INTERVAL_COUNT, 'interval') %> or more, each with at least 1 image.
<% end %>

<div class="container">
  <div class="col-md-6">
    <h3>Danish</h3>

    <p>
      <strong>Title:</strong> <%= @timeline.title_da %>
    </p>
  </div>

  <div class="col-md-6">
    <h3>Danish</h3>

    <p>
      <strong>Title:</strong>
      <% if @timeline.title_en.present? %>
        <%= @timeline.title_en %>
      <% else %>
        <em class="text-muted">Missing</em>
      <% end %>
    </p>
  </div>
</div>

<h2>Intervals</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Images</th>
      <th>Languages</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeline.intervals.each do |interval| %>
      <tr>
        <td>
          <%= link_to interval.title_da, interval %>
          <% if interval.title_en.present? %>
          <br>
          <span class="text-muted"><%= interval.title_en %></span>
          <% end %>
        </td>

        <td>
          <%= interval.subtitle_da %>
          <% if interval.subtitle_en.present? %>
          <br>
          <span class="text-muted"><%= interval.subtitle_en %></span>
          <% end %>
        </td>

        <td>
          <%= interval.interval_images.count %>
        </td>

        <td>
          <%= interval.bilingual? ? "Danish/English" : "Danish" %>
        </td>

        <td>
          <%= link_to "Edit", edit_interval_path(interval) %>
        </td>

        <td>
          <%= link_to 'Delete...', interval, method: :delete, data: { confirm: 'Are you sure you want to delete this interval?' }, class: "text-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to "Add interval...", new_timeline_interval_path(@timeline) %>
</p>