config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resource :account, except: [:new, :create]

  resources :users, except: [:edit, :update], constraints: { id: /\d+/ }
  devise_for :users

  resources :devices

  get 'assignments/:content_class/:content_id/select', controller: :assignments, action: :select, as: :select_device
  post 'assignments/assign', controller: :assignments, action: :assign, as: :assign_device

  resources :themes, shallow: true do
    resources :quizzes

    resources :timelines, shallow: true do
      resources :intervals, except: :index, shallow: true do
        resources :interval_images, except: :index
      end
    end

    resources :video_galleries, shallow: true do
      resources :videos, except: :index
    end

    resources :trailer_galleries, shallow: true do
      resources :trailers, except: :index
    end

    resources :galleries, shallow: true do
      resources :images, except: :index
    end

    resources :playlists, shallow: true do
      resources :tracks, except: [:index, :show]
    end
  end

  namespace :api do
    resources :devices, only: [:show, :update], constraints: { id: /[a-z0-9_-]+/i }

    get 'patron', to: 'cicero#show'
  end

  root to: 'themes#index'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  MIN_PRESENTABLE_TRACK_COUNT = 1

  include Assignable
  include Presentable

  belongs_to :theme, optional: true
  has_many :tracks, dependent: :destroy

  device_kind :audio

  validates :name, presence: true, uniqueness: true

  # overrides Presentable method
  def presentable?
    self.tracks.count >= MIN_PRESENTABLE_TRACK_COUNT
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include ThematicController

  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  def index
    @playlists = @theme.playlists.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = @theme.playlists.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  def create
    @playlist = @theme.playlists.new(playlist_params)

    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /playlists/1
  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /playlists/1
  def destroy
    @playlist.destroy

    redirect_to @playlist.theme, notice: 'Playlist was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_params
    params.require(:playlist).permit(:name, :description)
  end

end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, url: (playlist.new_record? ? [playlist.theme, playlist] : playlist), local: true) do |form| %>
  <%= render 'common/validation_errors', model: playlist %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: 'form-control', id: :playlist_name %>
    <span class="help-block">
      Required. The playlist name isn't shown publically, it's only for naming the playlist in the CMS.
    </span>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', id: :playlist_description %>
    <span class="help-block">
      Optional notes, not shown publically.
    </span>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= yield %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @playlist %>
<% end %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to playlist.name, playlist %></td>
        <td><%= playlist.description %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Delete', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add playlist...', new_theme_playlist_path(@theme) %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist do %>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Cancel', @playlist.theme %>
<% end %>

app/views/playlists/show.html.erb
<%= render 'common/assigned_devices', model: @playlist %>

<%= render 'common/content_title', model: @playlist do %>
  <%= link_to 'Edit playlist...', edit_playlist_path(@playlist) %> |
  <%= link_to 'Delete playlist...', @playlist, method: :delete, data: { confirm: 'Are you sure you want to delete this playlist and all its tracks?' }, class: "text-danger" %>
<% end %>

<p>
  <% if @playlist.presentable? %>
    <%= link_to "Assign to device...", select_device_path(content_class: @playlist.class.to_s.underscore, content_id: @playlist.to_param), class: "btn btn-default" %>
  <% else %>
    <%= link_to "Assign to device...", '#', class: "btn btn-default disabled" %>

    <span class="text-danger">
      This playlist is incomplete and cannot be previewed or assigned to devices yet.
      It must contain <%= pluralize(Playlist::MIN_PRESENTABLE_TRACK_COUNT, 'track') %> or more.
    </span>
  <% end %>
</p>


<% if @playlist.description.present? %>
  <%= simple_format @playlist.description %>
<% else %>
  <p><em class="text-muted">No description.</em></p>
<% end %>

<h2>Tracks</h2>

<% if @playlist.tracks.any? %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Notes</th>
        <th style="width: 10%"></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
    <% @playlist.tracks.each do |track| %>

      <tr>
        <td>
          <%= track.title %>
          <br>
          <span class="text-muted">
            Displayed title: <samp><%= track.display_title %></samp>
          </span>
        </td>
        <td>
          <%= track.description %>
        </td>
        <td>
          <audio src="<%= track.mp3.url %>" controls />
        </td>
        <td>
          <%= link_to "Edit", edit_track_path(track) %>
        </td>
        <td>
          <%= link_to 'Delete...', track, method: :delete, data: { confirm: 'Are you sure you want to delete this track?' }, class: "text-danger" %>
        </td>
      </tr>

    <% end %>
    </tbody>
  </table>

<% else %>
  <div class="alert alert-warning">
    This playlist cannot be assigned to any devices yet, as it must contain at least 1 track.
  </div>
<% end %>

<p>
  <%= link_to 'Add track...', new_playlist_track_path(@playlist) %>
</p>